# Generated by Django 2.2.1 on 2019-06-04 11:18

import bfblog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superuser',
            name='nick',
        ),
        migrations.AddField(
            model_name='superuser',
            name='user_image',
            field=models.ImageField(default='default.png', upload_to=bfblog.models.PathandRename('profile_pics'), verbose_name='User Image'),
            preserve_default=False,
        ),
    ]
