# Generated by Django 2.2.1 on 2019-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfpaste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='author',
            field=models.TextField(default='testuser'),
            preserve_default=False,
        ),
    ]
