# Generated by Django 2.2.1 on 2019-05-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfpaste', '0002_paste_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='author',
            field=models.TextField(max_length=50),
        ),
    ]
