# Generated by Django 2.2.1 on 2019-05-28 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bfpaste', '0003_auto_20190528_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 14, 17, 50, 251646, tzinfo=utc), verbose_name='Publising date'),
        ),
    ]
