# Generated by Django 2.2.1 on 2019-05-28 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bfpaste', '0004_auto_20190528_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paste',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 17, 31, 10, 749238, tzinfo=utc), verbose_name='Publising date'),
        ),
    ]
