# Generated by Django 2.2.1 on 2019-05-28 20:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bfpaste', '0005_auto_20190528_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='lang',
            field=models.CharField(default='python', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paste',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='paste',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 20, 54, 51, 886402, tzinfo=utc), verbose_name='Publising date'),
        ),
    ]
