# Generated by Django 2.2.1 on 2019-05-29 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bfpaste', '0006_auto_20190528_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='paste_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='paste',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 12, 35, 47, 998901, tzinfo=utc), verbose_name='Publising date'),
        ),
    ]
