# Generated by Django 2.2.1 on 2019-05-29 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bfpaste', '0007_auto_20190529_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='paste_id',
            field=models.UUIDField(default='7f4f48455b073597a126', editable=False),
        ),
        migrations.AlterField(
            model_name='paste',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 12, 39, 20, 788253, tzinfo=utc), verbose_name='Publising date'),
        ),
    ]
