# Generated by Django 2.2.1 on 2019-05-29 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bfpaste', '0010_auto_20190529_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='paste_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='paste',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 13, 2, 48, 98247, tzinfo=utc), verbose_name='Publising date'),
        ),
    ]
