# Generated by Django 2.2.1 on 2019-05-30 22:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bfpaste', '0011_auto_20190529_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paste',
            options={'verbose_name': 'Paste'},
        ),
        migrations.AlterField(
            model_name='paste',
            name='lang',
            field=models.CharField(choices=[('c', 'C'), ('c++', 'C++'), ('css', 'CSS'), ('java', 'Java'), ('javascript', 'JavaScript'), ('python', 'Python')], default=('c', 'C'), max_length=100, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 30, 22, 59, 8, 607169, tzinfo=utc), verbose_name='Publising date'),
        ),
    ]
