# Generated by Django 2.2.1 on 2019-05-30 22:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bfpaste', '0012_auto_20190531_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 30, 22, 59, 23, 562568, tzinfo=utc), verbose_name='Publising date'),
        ),
    ]
